sources:
    andorra:
        seed: http://download.geofabrik.de/europe/andorra-latest.osm.pbf
        update: http://download.geofabrik.de/europe/andorra-updates/

layers:
    - id: communes
      name: Communes
      admin_levels: [7]
