sources:
    belgium:
        seed: http://download.geofabrik.de/europe/belgium-latest.osm.pbf
        update: http://download.geofabrik.de/europe/belgium-updates/
    luxembourg:
        seed: http://download.geofabrik.de/europe/luxembourg-latest.osm.pbf
        update: http://download.geofabrik.de/europe/luxembourg-updates/
    netherlands:
        seed: http://download.geofabrik.de/europe/netherlands-latest.osm.pbf
        update: http://download.geofabrik.de/europe/netherlands-updates/

layers:
    - id: cities
      name: Cities
      admin_levels: [8]
      simplify: 6
    - id: regions
      name: Regions
      admin_levels: [4, 6]
      simplify: 4
    - id: countries
      name: Countries
      admin_levels: [2]
      simplify: 3
