FROM fedora:28

RUN dnf -y install geos-devel zlib bzip2 snappy libstdc++-devel make which gcc-c++ perl findutils zlib-devel bzip2-devel snappy-devel && \
    mkdir -p /tmp/build && \
    cd /tmp/build && \
    curl -L -o rocksdb.tar.gz https://github.com/facebook/rocksdb/archive/master.tar.gz && \
    tar xzpf rocksdb.tar.gz && \
    rm rocksdb.tar.gz && \
    cd rocksdb-* && \
    make -j 8 shared_lib && \
    make install-shared && \
    echo '/usr/local/lib' > /etc/ld.so.conf.d/local.conf && \
    cd / && \
    rm -rf /tmp/build && \
    dnf -y remove make which perl findutils && \
    dnf clean all
