FROM docker.io/rubenv/osmtopo-base

RUN curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo > /etc/yum.repos.d/yarn.repo && \
    dnf -y install golang git nodejs yarn && \
    dnf clean all

ENV GOPATH /go
WORKDIR /go/src/github.com/rubenv/osmtopo
