FROM fedora:27

RUN dnf -y install geos-devel zlib bzip2 snappy && \
    dnf -y install make which gcc-c++ perl findutils zlib-devel bzip2-devel snappy-devel && \
    mkdir -p /tmp/build && \
    cd /tmp/build && \
    curl -L -o rocksdb.tar.gz https://github.com/facebook/rocksdb/archive/master.tar.gz && \
    tar xzpf rocksdb.tar.gz && \
    rm rocksdb.tar.gz && \
    cd rocksdb-* && \
    make -j 4 shared_lib && \
    make install-shared && \
    cd / && \
    rm -rf /tmp/build && \
    dnf -y remove make which perl findutils gcc-c++ && \
    dnf clean all
